dotenv:
  directory: ../

server:
  port: 8082

spring:
  application:
    name: course-service

  data:
    mongodb:
      uri: ${MONGODB_COURSE_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://keycloak:8181/realms/lms/protocol/openid-connect/certs}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

paypal:
  mode: ${PAYPAL_MODE}
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}