dotenv:
  directory: ../

server:
  port: 8082

spring:
  application:
    name: course-service

  data:
    mongodb:
      uri: ${MONGODB_COURSE_URI}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    instance-id: ${EUREKA_INSTANCE_HOSTNAME:localhost}:443
    status-page-url: https://${EUREKA_INSTANCE_HOSTNAME:localhost}/actuator/info
    health-check-url: https://${EUREKA_INSTANCE_HOSTNAME:localhost}/actuator/health
    home-page-url: https://${EUREKA_INSTANCE_HOSTNAME:localhost}/

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

paypal:
  mode: ${PAYPAL_MODE}
  client-id: ${PAYPAL_CLIENT_ID}
  client-secret: ${PAYPAL_CLIENT_SECRET}