dotenv:
  directory: ../

server:
  port: 8081

spring:
  application:
    name: user-service

  data:
    mongodb:
      uri: ${MONGODB_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/lms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

keycloak:
  admin:
    server-url: http://localhost:8181
    realm: lms
    client-id: lms-user-service
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}