dotenv:
  directory: ../

server:
  port: 8083

spring:
  application:
    name: quiz-service

  data:
    mongodb:
      uri: ${MONGODB_QUIZ_URI}

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: 443
    status-page-url: https://${EUREKA_INSTANCE_HOSTNAME:localhost}/actuator/info
    health-check-url: https://${EUREKA_INSTANCE_HOSTNAME:localhost}/actuator/health
    home-page-url: https://${EUREKA_INSTANCE_HOSTNAME:localhost}/

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings